### ISSUE TITLE
Active connections to kuzzle

### ISSUE THREAD

**Issue by andrewmunro** [kuzzleio/kuzzle-plugin-prometheus#4]
We get how many rooms have been created with kuzzle, but we don't actually have a metric for how many individual connections each kuzzle node is currently handling.

Could we get this added?

**Comment by alexandrebouthinon** [comment]
Hi @andrewmunro, we added the `connection:new` and `connection:remove` in Kuzzle 1.10 . I'll implement that new metric soon :+1:

**Comment by andrewmunro** [comment]
Awesome 🎉 !

**Comment by alexandrebouthinon** [comment]
It's released https://github.com/kuzzleio/kuzzle-plugin-prometheus/releases/tag/1.2.0
